graph TD
    %% System Identification
    subgraph External["fa:fa-globe Internet"]
        User((fa:fa-user User))
    end
    subgraph Cluster["fa:fa-dharmachakra Kind Cluster"]
        direction TB
        subgraph Entry["fa:fa-door-open Entry Points"]
            GW_api-gateway["fa:fa-door-open Gateway: api-gateway"]
        end

        subgraph Services["fa:fa-link Network Services"]
            SVC_falco-falcosidekick["fa:fa-share-alt Svc: falco-falcosidekick"]
            SVC_k-api-service["fa:fa-share-alt Svc: k-api-service"]
            SVC_kubernetes["fa:fa-share-alt Svc: kubernetes"]
            SVC_grafana["fa:fa-share-alt Svc: grafana"]
            SVC_istio-ingressgateway["fa:fa-share-alt Svc: istio-ingressgateway"]
            SVC_istiod["fa:fa-share-alt Svc: istiod"]
            SVC_loki["fa:fa-share-alt Svc: loki"]
            SVC_loki-headless["fa:fa-share-alt Svc: loki-headless"]
            SVC_loki-memberlist["fa:fa-share-alt Svc: loki-memberlist"]
            SVC_prometheus["fa:fa-share-alt Svc: prometheus"]
            SVC_kube-dns["fa:fa-share-alt Svc: kube-dns"]
            SVC_loki-stack["fa:fa-share-alt Svc: loki-stack"]
            SVC_loki-stack-headless["fa:fa-share-alt Svc: loki-stack-headless"]
            SVC_loki-stack-memberlist["fa:fa-share-alt Svc: loki-stack-memberlist"]
        end

        subgraph Workloads["fa:fa-microchip Pods & Sidecars"]
            subgraph POD_breach_test["Pod: breach_test"]
                C_breach_test_["fa:fa_box breach_test"]
                C_istio_proxy_["fa:fa_box istio_proxy"]
            end
            
            subgraph POD_falco_f4ts2["Pod: falco_f4ts2"]
                C_falco_["fa:fa_box falco"]
                C_falcoctl_artifact_follow_["fa:fa_box falcoctl_artifact_follow"]
                C_istio_proxy_["fa:fa_box istio_proxy"]
            end
            
            subgraph POD_falco_falcosidekick_7b7dbbd79_kk99g["Pod: falco_falcosidekick_7b7dbbd79_kk99g"]
                C_falcosidekick_["fa:fa_box falcosidekick"]
                C_istio_proxy_["fa:fa_box istio_proxy"]
            end
            
            subgraph POD_falco_falcosidekick_7b7dbbd79_p7f8b["Pod: falco_falcosidekick_7b7dbbd79_p7f8b"]
                C_falcosidekick_["fa:fa_box falcosidekick"]
                C_istio_proxy_["fa:fa_box istio_proxy"]
            end
            
            subgraph POD_k_api_5b5ffc84b8_mnfcw["Pod: k_api_5b5ffc84b8_mnfcw"]
                C_k_api_["fa:fa_box k_api"]
                C_istio_proxy_["fa:fa_box istio_proxy"]
            end
            
            subgraph POD_k_api_5b5ffc84b8_zcjsf["Pod: k_api_5b5ffc84b8_zcjsf"]
                C_k_api_["fa:fa_box k_api"]
                C_istio_proxy_["fa:fa_box istio_proxy"]
            end
            
            subgraph POD_grafana_7874f88995_cn5hl["Pod: grafana_7874f88995_cn5hl"]
                C_grafana_["fa:fa_box grafana"]
            end
            
            subgraph POD_istio_ingressgateway_84f78c778b_tqkmd["Pod: istio_ingressgateway_84f78c778b_tqkmd"]
                C_istio_proxy_["fa:fa_box istio_proxy"]
            end
            
            subgraph POD_istiod_67b9cf4965_s6hlr["Pod: istiod_67b9cf4965_s6hlr"]
                C_discovery_["fa:fa_box discovery"]
            end
            
            subgraph POD_loki_0["Pod: loki_0"]
                C_loki_sc_rules_["fa:fa_box loki_sc_rules"]
                C_loki_["fa:fa_box loki"]
            end
            
            subgraph POD_prometheus_86f99d868_9q566["Pod: prometheus_86f99d868_9q566"]
                C_prometheus_server_configmap_reload_["fa:fa_box prometheus_server_configmap_reload"]
                C_prometheus_server_["fa:fa_box prometheus_server"]
            end
            
            subgraph POD_coredns_5d78c9869d_dhbm6["Pod: coredns_5d78c9869d_dhbm6"]
                C_coredns_["fa:fa_box coredns"]
            end
            
            subgraph POD_coredns_5d78c9869d_vddpg["Pod: coredns_5d78c9869d_vddpg"]
                C_coredns_["fa:fa_box coredns"]
            end
            
            subgraph POD_etcd_api_cluster_control_plane["Pod: etcd_api_cluster_control_plane"]
                C_etcd_["fa:fa_box etcd"]
            end
            
            subgraph POD_kindnet_bb4j5["Pod: kindnet_bb4j5"]
                C_kindnet_cni_["fa:fa_box kindnet_cni"]
            end
            
            subgraph POD_kube_apiserver_api_cluster_control_plane["Pod: kube_apiserver_api_cluster_control_plane"]
                C_kube_apiserver_["fa:fa_box kube_apiserver"]
            end
            
            subgraph POD_kube_controller_manager_api_cluster_control_plane["Pod: kube_controller_manager_api_cluster_control_plane"]
                C_kube_controller_manager_["fa:fa_box kube_controller_manager"]
            end
            
            subgraph POD_kube_proxy_mbt7w["Pod: kube_proxy_mbt7w"]
                C_kube_proxy_["fa:fa_box kube_proxy"]
            end
            
            subgraph POD_kube_scheduler_api_cluster_control_plane["Pod: kube_scheduler_api_cluster_control_plane"]
                C_kube_scheduler_["fa:fa_box kube_scheduler"]
            end
            
            subgraph POD_local_path_provisioner_6bc4bddd6b_fgvtn["Pod: local_path_provisioner_6bc4bddd6b_fgvtn"]
                C_local_path_provisioner_["fa:fa_box local_path_provisioner"]
            end
            
            subgraph POD_loki_69cc446978_k78z4["Pod: loki_69cc446978_k78z4"]
                C_loki_["fa:fa_box loki"]
            end
            
            subgraph POD_promtail_gwdxg["Pod: promtail_gwdxg"]
                C_promtail_["fa:fa_box promtail"]
            end
        end
        
        subgraph Security["fa:fa-shield-alt Security Stack"]
            Falco_DS[fa:fa-user-secret Falco DaemonSet]
            Sidekick[fa:fa-comment-dots Falcosidekick]
            Loki_DB[(fa:fa-database Loki DB)]
        end
    end
    %% Traffic Flow
    User --> CF[fa:fa-cloud Cloudflare Tunnel]
    CF --> GW_api-gateway
    SVC_falco-falcosidekick -.-> POD_falco_falcosidekick_7b7dbbd79_kk99g
    SVC_falco-falcosidekick -.-> POD_falco_falcosidekick_7b7dbbd79_p7f8b
    SVC_k-api-service -.-> POD_k_api_5b5ffc84b8_mnfcw
    SVC_k-api-service -.-> POD_k_api_5b5ffc84b8_zcjsf
    SVC_kubernetes -.-> POD_kube_apiserver_api_cluster_control_plane
    SVC_grafana -.-> POD_grafana_7874f88995_cn5hl
    SVC_istio-ingressgateway -.-> POD_istio_ingressgateway_84f78c778b_tqkmd
    SVC_istiod -.-> POD_istiod_67b9cf4965_s6hlr
    SVC_loki -.-> POD_loki_0
    SVC_loki -.-> POD_loki_69cc446978_k78z4
    SVC_loki-headless -.-> POD_loki_0
    SVC_loki-headless -.-> POD_loki_69cc446978_k78z4
    SVC_loki-memberlist -.-> POD_loki_0
    SVC_loki-memberlist -.-> POD_loki_69cc446978_k78z4
    SVC_prometheus -.-> POD_prometheus_86f99d868_9q566
    SVC_kube-dns -.-> POD_coredns_5d78c9869d_dhbm6
    SVC_kube-dns -.-> POD_coredns_5d78c9869d_vddpg
    SVC_loki-stack -.-> POD_loki_0
    SVC_loki-stack -.-> POD_loki_69cc446978_k78z4
    SVC_loki-stack-headless -.-> POD_loki_0
    SVC_loki-stack-headless -.-> POD_loki_69cc446978_k78z4
    SVC_loki-stack-memberlist -.-> POD_loki_0
    SVC_loki-stack-memberlist -.-> POD_loki_69cc446978_k78z4
    %% Security Observability
    Workloads -. syscalls .-> Falco_DS
    Falco_DS --> Sidekick
    Sidekick --> Loki_DB
end