apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vector-to-clickhouse
  namespace: logging
spec:
  podSelector:
    matchLabels:
      app: vector
  policyTypes: [Egress]
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: clickhouse
    ports:
    - protocol: TCP
      port: 8123
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-system-dns
  namespace: logging
spec:
  podSelector:
    matchLabels:
      app: vector
  policyTypes: [Egress]
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53