# Allow internal traffic within the logging namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-logging-internal
  namespace: logging
spec:
  podSelector: {}
  policyTypes: [Egress, Ingress]
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - podSelector: {}

---
# Allow Promtail to talk to K8s API
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-logging-to-api
  namespace: logging
spec:
  podSelector: { matchLabels: { app: promtail } }
  policyTypes: [Egress]
  egress:
  - to:
    - namespaceSelector: { matchLabels: { kubernetes.io/metadata.name: kube-system } }
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443

---
# Allow DNS (Required for loki-stack resolution)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-logging-dns
  namespace: logging
spec:
  podSelector: {}
  policyTypes: [Egress]
  egress:
  - to: [{ namespaceSelector: { matchLabels: { kubernetes.io/metadata.name: kube-system } } }]
    ports: 
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53