apiVersion: v1
kind: Service
metadata:
  name: k-api-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: k-api  # Ensure this matches the label in your deployment.yaml
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080 # This "pins" the service to localhost:30080